### ISSUE TITLE
Example for Karma Coverage?

### ISSUE THREAD

**Issue by nottinhill** [caitp/karma-coveralls#39]
Hi thanks for your work on this plugin. I now installed the plugin and sent my built to codeship and also let Karma run beforehand locally, but I dont see any coverage generated. I do not have Mocha, this is a Ionic3/Angular4 project employing only Karma. Do you have an example config for use with Karma (and Codeship)?

**Comment by caitp** [comment]
I am not familiar with CodeShip, sorry.

**Comment by nottinhill** [comment]
My concrete problem is, that we are using typescript.

This is my Karma.conf.js and it is just scanning my polyfills.js for coverage:


```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-coverage'),
            require('karma-coveralls'),
            require('@angular/cli/plugins/karma')
        ],
        client: {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        files: [{
                pattern: './src/test.ts',
                watched: false
            }
        ],
        preprocessors: {
            './src/test.ts': ['@angular/cli']
        },
        mime: {
            'text/x-typescript': ['ts', 'tsx']
        },
        coverageReporter: {
            type: 'lcov', // lcov or lcovonly are required for generating lcov.info files
            dir: 'coverage/'
        },
        angularCli: {
            environment: 'dev'
        },
        reporters: ['coverage', 'coveralls'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false
    });
};

```

**Comment by nottinhill** [comment]
Coverall is only testing my test.ts or my polyfills.js, nothing else.

**Comment by caitp** [comment]
I mean, I really don't have the answer to this question :( this project sort of predated adoption of TypeScript, from the angular 1.x days. I haven't had the opportunity or need to adapt it to TypeScript just yet.

If you've gotten anywhere with integrating it, I would love it if you could send a pull request (and hopefully some tests to demonstrate that it's doing the right thing correctly, maybe some doc updates for typescript users).

I know it's been a while since this issue was opened, but if anybody else looking at this has time to chip in and make it happen, that would be amazing.

**Comment by nottinhill** [comment]
We employ human testers now, since Developers are lazy and Project Managers come from Mars.

**Comment by caitp** [comment]
well alright then, leaving this open in case anybody else has a similar problem and can stand to submit a fix.

**Comment by jgravois** [comment]
its a bit of a beast, but you can see a working TypeScript implementation that generates coverage reports here.

https://github.com/Esri/arcgis-rest-js/blob/master/karma.conf.js

**Comment by MarkPThomas** [comment]
For me it causes Chrome to throw an exception when running Karma. Testing works if I don't include the 'coveralls' reporter, but when I add it as instructed in the yaml, I get the following:

`16 05 2018 10:57:28.747:INFO [karma]: Karma v2.0.2 server started at http://0.0.0.0:9876/
16 05 2018 10:57:28.748:INFO [launcher]: Launching browser Chrome with unlimited concurrency
16 05 2018 10:57:28.754:INFO [launcher]: Starting browser Chrome
16 05 2018 10:57:31.204:INFO [Chrome 66.0.3359 (Windows 10 0.0.0)]: Connected on socket terYi1eNZPTHl5v_AAAA with id 10964639
Unhandled rejection TypeError: Cannot read property 'push' of undefined
    at D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\karma\lib\reporters\multi.js:6:25
    at Array.forEach (<anonymous>)
    at MultiReporter.addAdapter (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\karma\lib\reporters\multi.js:5:15)
    at Server.<anonymous> (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\karma\lib\middleware\runner.js:41:18)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Server.emit (events.js:211:7)
    at Executor.schedule (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\karma\lib\executor.js:26:15)
    at D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\karma\lib\middleware\runner.js:91:22
    at tryCatcher (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\wamp_remote\notOnWebsite\continuous-integration-js\node_modules\bluebird\js\release\promise.js:432:57)`

**Comment by caitp** [comment]
whats the intellij thing coming from?
